### ISSUE TITLE
We notice "Pydantic Import Error" Sweep: 

### ISSUE THREAD

**Issue by suryasiriki1** [HexyeDEV/Telegram-Chatbot-Gpt4Free#13]
### Details

![image](https://github.com/HexyeDEV/Telegram-Chatbot-Gpt4Free/assets/122189232/42e092bb-2894-4ba2-899e-312f99fdb60d)

<details open>
<summary>Checklist</summary>

- [X] `requirements.txt`
> • Add "pydantic==1.8.2" to the list of required packages.

</details>

**Comment by suryasiriki1** [comment]
ERROR: Cannot install chromadb==0.3.26 and pydantic==1.8.2 because these package versions have conflicting dependencies.

**Comment by HexyeDEV** [comment]
Looks more like an issue with python version
