### ISSUE TITLE
Sweep: Fix Dockerfile for python-hnswlib Installation

### ISSUE THREAD

**Issue by AlexanderKorataev** [HexyeDEV/Telegram-Chatbot-Gpt4Free#19]
### Details

The problem was related to the installation of the python-hnswlib package in the Docker container. Additionally, there was a duplicated line in the Dockerfile, which needed to be removed.

I fixed the installation issue by ensuring that the python-hnswlib package could be successfully installed in the Docker container. I also removed the duplicate line:

RUN pip install --no-cache-dir -r requirements.txt

<details open>
<summary>Checklist</summary>

- [X] ``Dockerfile`` ✅ Commit <a href='https://github.com/HexyeDEV/Telegram-Chatbot-Gpt4Free/commit/be0aa51bea71731afaf6bcb3b0008d2dbb41e45b'><code>be0aa51</code></a>
- [X] `Dockerfile` ❌ Sandbox failed so I made additional changes
- [X] ``requirements.txt`` ⚠️ No Changes Made
- [X] `requirements.txt` ❌ Sandbox failed so I made additional changes
- [X] `Dockerfile` ❌ Sandbox failed so I made additional changes
- [X] `requirements.txt` ❌ Sandbox failed so I made additional changes
</details>

**Comment by obscure88** [comment]
hi
